on:
  push:
    branches:
      - main
    paths:
      - cvepred/**/*
      - Dockerfile
      - "*.ipynb"
      - pyproject.toml
      - poetry.lock
      - .github/workflows/docker.yml
  pull_request:
    branches:
      - main

jobs:
  create-container:
    environment: testing
    runs-on: ubuntu-latest

    steps:
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZ_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - uses: actions/checkout@v4

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: kpostekk/cvepred:latest
          target: api
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
